<?php
// Gallery2 Image Chooser pop-up window German lang variables - Version 2.2

// If you translate this file to your own language, please zip it and e-mail
// it to blogger (at sign) steffensenfamily (dot) com and I'll make it available
// for others and include it in the next version.  Thanks!

$g2ic_lang = array(
'about' => '&Uuml;ber G2Image',
'alignment_class' => 'Alignment Class:',
'alignment_legend' => 'Alignment Class (CSS muss die g2image classes unterst&uuml;tzen um aktiv zu werden):',
'click_advanced' => '&Ouml;ffne das erweiterte Options Men&uuml;',
'click_image' => 'Klicke auf ein Bild f&uuml;r die Bild optionen.',
'click_one_click' => 'Mit den standard Einstellungen einf&uuml;gen',
'click_options' => 'W&auml;hle das Ereigniss wenn auf ein Bild geklickt wird:',
'current_album' => 'Aktuelles Album:',
'custom_url' => 'Andere URL:',
'description' => 'Beschreibung:',
'description_legend' => 'Text f&uuml;r das Bild alternativer Text oder Text link:',
'display_legend' => 'Optionen anzeigen',
'drupal_album_legend' => 'Einen Drupal G2 Filter tag f&uuml;r das aktuelle Album einf&uuml;gen:',
'drupal_g2_filter' => 'Drupal Gallery2 Filter',
'empty_album' => 'Es befinden sich keine Fotos in diesem Album.<br /><br />Bitte w&auml;hle ein anderes Album aus der oberen Navigation.',
'filename' => 'Dateiname: ',
'filenames' => 'Dateinamen',
'g2_directory_error' => 'Kann das Gallery2 data Verzeichnis nicht &ouml;ffnen.',
'g2_embedded_error' => '<h3>Fatal Gallery2 Error: Cannot activate the Gallery2 Embedded functions.</h3><br />For WordPress users, either install the WPG2 plugin
(located at <a href="http://wpg2.galleryembedded.com/">http://wpg2.galleryembedded.com/</a>) or verify your Gallery2 path in the G2Image Popup Options admin panel.<br /><br />For other platforms, please verify your Gallery2 path in config.php.',
'g2_entities_by_id_error' => '<h3>Fatal Gallery2 Error: Cannot get image info for this Gallery2 ID.</h3><br />Here\'s the error from G2: ',
'g2_fatal_error' => '<h3>Fatal Gallery2 error:</h3><br />Here\'s the error from G2: ',
'g2_id_by_path_error' => '<br /><h3>Gallery2 Error: Cannot get the Gallery2 ID for the requested path.</h3><br />This is most likely due to a file or
directory residing in your Gallery2 data directory structure, but not being registered in Gallery2 as part of your album structure.  All the rest of the
functionality on this page will work.<br /><br />Here\'s the path that is invalid: ',
'g2_id_not_found_error' => '<h3>Fatal Gallery2 Error: Cannot get the Gallery2 ID for this file.</h3>Here\'s the error from G2: ',
'g2_image_title' => 'Gallery2 Titel:',
'go' => 'W&auml;hle',
'how_insert' => 'Wie einf&uuml;gen:',
'image_title' => 'Titel: ',
'img_float_left' => 'Links ausrichten',
'img_float_right' => 'Rechts ausrichten',
'img_centered' => 'Zentriert',
'img_none' => 'Keine',
'img_normal' => 'Normal',
'insert' => 'Einf&uuml;gen',
'insert_legend' => 'Dr&uuml;cke die Schaltfl&auml;che um das Bild einzuf&uuml;gen:',
'last_modification_new' => 'Letzte Ver&auml;nderung (neuste zuerst)',
'last_modification_old' => 'Letzte Ver&auml;nderung (&auml;lteste zuerst)',
'link_album' => 'Text link zum &uuml;bergeordneten Album',
'link_image' => 'Text link zum Bild',
'name_a_to_z' => 'Dateiname (A-z)',
'name_z_to_a' => 'Dateiname (z-A)',
'page' => 'Seite:',
'page_navigation' => 'Seiten Navigation:',
'photo_albums' => 'Foto Alben',
'redraw' => 'Erneuern',
'sort_error' => 'Fehler sortiert nach',
'sorted_by' => 'sortiert nach:',
'subalbums' => 'Unteralben:',
'thumbnails' => 'Vorschaubilder',
'thumbnail_album' => 'Vorschaubild mit Link zum &uuml;bergeordneten Album',
'thumbnail_custom_url' => 'Vorschaubild mit Link zu einer anderen URL (aus der unteren Textbox)',
'thumbnail_image' => 'Vorschaubild mit Link zum Bild',
'thumbnail_only' => 'Nur Vorschaubild - Kein Link',
'thumbnails_per_page' => 'Pro Seite:',
'title' => 'Gallery 2 Image Chooser',
'title_a_to_z' => 'Gallery2 Titel (A-z)',
'title_z_to_a' => 'Gallery2 Titel (z-A)',
'url' => 'URL:',
'wpg2_album_legend' => 'Einen WPG2 tag f&uuml;r das aktuell Album einf&uuml;gen:',
'wpg2_configuration_error' => 'Configuration Error:<br />WPG2 is present and active, but not validated.<br />Please configure and validate WPG2 in the
WordPress admin panel.<br />Anweisungen bewinden sich bei http://wpg2.galleryembedded.com.',
'wpg2_link_album' => 'Text link zum &uuml;bergeordneten Album (HTML)',
'wpg2_link_image' => 'Text link zum Bild (HTML)',
'wpg2_tag_image' => 'WPG2 tag des Bildes',
'wpg2_thumbnail_album' => 'Vorschaubild mit Link zum &uuml;bergeordneten Album (HTML)',
'wpg2_thumbnail_custom_url' => 'Vorschaubild mit Link zu einer anderen URL (aus der unteren Textbox) (HTML)',
'wpg2_thumbnail_image' => 'Vorschaubild mit Link zum Bild (HTML)',
'wpg2_thumbnail_only' => 'Nur Vorschaubild - Kein Link (HTML)',
//
// New for version 2.2
//
'fullsize_image' => 'Fullsized image with link to Gallery page for image',
'fullsize_only' => 'Fullsized image only - no link',
'image_size' => 'Image Size',
'image_size_instructions' => 'Leave size blank the current default size of ',
'orignination_time_new' => 'Origination Time (Newest First)',
'orignination_time_old' => 'Origination Time (Oldest First)',
'thumbnail_lightbox' => 'Thumbnail with LightBox link to Fullsized Image',
'titles' => 'Titles',
'wpg2_fullsize_image' => 'Fullsized image with link to Gallery page for image (HTML)',
'wpg2_fullsize_only' => 'Fullsized image only - no link (HTML)',
'wpg2_thumbnail_lightbox' => 'Thumbnail with LightBox link to Fullsized Image (HTML)')
?>