<?php

// Hungarian lang variables - Version 2.2

// If you translate this file to your own language, please zip it and e-mail
// it to blogger (at sign) steffensenfamily (dot) com and I'll make it available
// for others and include it in the next version.  Thanks!

// translated by andianhu Andi Vida 25/07/2007

$g2ic_lang = array(
'about' => 'A G2Image-rõl',
'alignment_class' => 'Igazítás osztálya:',
'alignment_legend' => 'Igazítás osztálya (CSS-támogatás kell a g2image osztályok hatékony mûködéséhez):',
'click_advanced' => 'Nyissa ki a Haladó beállítások menüt',
'click_image' => 'A kép beállításaihoz kattintson egy képre.',
'click_one_click' => 'Beszúrás az alapbeállítások szerint',
'click_options' => 'Kattintson egy képre, majd eszerint válasszon:',
'current_album' => 'Jelenlegi album:',
'custom_url' => 'Testreszabott URL:',
'description' => 'Leírás:',
'description_legend' => 'Alternatív text vagy szöveglink a képhez:',
'display_legend' => 'Megjelenítési beállítások',
'drupal_album_legend' => 'Szúrjon be Drupal G2-szûrõt ehhez az albumhoz:',
'drupal_g2_filter' => 'Drupal Gallery2 szûrõ',
'empty_album' => 'Ebben az albumban nincsenek fotók.<br /><br />Válasszon másik albumot a fenti navigációs menübõl.',
'filename' => 'Filenév: ',
'filenames' => 'Filenevek',
'g2_directory_error' => 'A Gallery2 adatkönyvtár nem nyitható meg.',
'g2_embedded_error' => '<h3>Fatális Gallery2 hiba: a Gallery2 beágyazott funkciói nem aktiválhatók.</h3><br />WordPress-felhasználók kapcsolják be a WPG2-t az adminisztrációs felület Plugin-beállításainál.<br /><br />Más platformokhoz a config.php-ben kell engedélyezni a Gallery2 útvonalát.',
'g2_entities_by_id_error' => '<h3>Fatális Gallery2 hiba: ehhez a Gallery2 ID-hez nincs elérhetõ képinformáció. </h3><br />A G2 hibaüzenete: ',
'g2_fatal_error' => '<h3>Fatális Gallery2 hiba:</h3><br />A G2 hibaüzenete: ',
'g2_id_by_path_error' => '<br /><h3>Gallery2 hiba: ezen az útvonalon nem érhetõ el Gallery2 ID.</h3><br />Ennek valószínûleg az az oka, hogy az ön Gallery2-jének adatkönyvtár-szerkezetében van olyan file vagy könyvtár, ami nincs regisztrálva a Gallery2-ben az ön albumfelépítése részeként. Az összes többi funkció mûködik ezen az oldalon.<br /><br />Az érvénytelen útvonal: ',
'g2_id_not_found_error' => '<h3>Fatális Gallery2 hiba: ehhez a file-hoz nincs elérhetõ Gallery2 ID.</h3>A G2 hibaüzenete: ',
'g2_image_title' => 'Gallery2 címe:',
'go' => 'Menj',
'how_insert' => 'Beszúrás módja:',
'image_title' => 'Cím: ',
'img_float_left' => 'Balra igazítás',
'img_float_right' => 'Jobbra igazítás',
'img_centered' => 'Középre',
'img_none' => 'Egyik sem',
'img_normal' => 'Normál',
'insert' => 'Beszúrás',
'insert_legend' => 'A kép beszúrásához nyomja meg a gombot:',
'last_modification_new' => 'Utolsó módosítás (elõre a legújabbat)',
'last_modification_old' => 'Utolsó módosítás (elõre a legrégebbit)',
'link_album' => 'Szülõalbumhoz tartozó szöveg',
'link_image' => 'Képaláírás',
'name_a_to_z' => 'Filenév (A-z)',
'name_z_to_a' => 'Filenév (z-A)',
'page' => 'Oldal:',
'page_navigation' => 'Oldal navigáció:',
'photo_albums' => 'Fotóalbumok',
'redraw' => 'Újrarajzolás',
'sort_error' => 'Hibacsoportosítás módja: ',
'sorted_by' => 'Csoportosítás alapja:',
'subalbums' => 'Al-bumok:',
'thumbnails' => 'Bélyegképek',
'thumbnail_album' => 'Bélyegkép a szülõalbum linkjével',
'thumbnail_custom_url' => 'Bélyegkép az egyéni URL linkjével (a lenti szövegdobozból)',
'thumbnail_image' => 'Bélyegkép a kép linkjével',
'thumbnail_only' => 'Bélyegkép link nélkül',
'thumbnails_per_page' => 'Oldalanként:',
'title' => 'Gallery 2 Képválasztó',
'title_a_to_z' => 'Gallery2 Cím (A-z)',
'title_z_to_a' => 'Gallery2 Cím (z-A)',
'url' => 'URL:',
'wpg2_album_legend' => 'WPG2 tag beszúrása ehhez az albumhoz:',
'wpg2_configuration_error' => 'Konfigurációs hiba:<br />a WPG2 itt van és aktív, de nincs bekapcsolva.<br />Kérem, konfigurálja és kapcsolja be a WordPress admin-felületén a Pluginok beállításainál. <br />Ehhez leírás a http://wpg2.galleryembedded.com. címen',
'wpg2_link_album' => 'A szülõalbumhoz tartozó szöveg (HTML)',
'wpg2_link_image' => 'A képhez tartozó szöveg (HTML)',
'wpg2_tag_image' => 'WPG2 kép-tag',
'wpg2_thumbnail_album' => 'Szülõalbumhoz tartozó bélyegkép (HTML)',
'wpg2_thumbnail_custom_url' => '(A lenti szövegdobozból vett) egyéni URL-hez tartozó bélyegkép (HTML)',
'wpg2_thumbnail_image' => 'Képhez tartozó bélyegkép (HTML)',
'wpg2_thumbnail_only' => 'Kapcsolat nélküli bélegkép (HTML)',
//
// New for version 2.2
//
'fullsize_image' => 'Fullsized image with link to Gallery page for image',
'fullsize_only' => 'Fullsized image only - no link',
'image_size' => 'Image Size',
'image_size_instructions' => 'Leave size blank the current default size of ',
'orignination_time_new' => 'Origination Time (Newest First)',
'orignination_time_old' => 'Origination Time (Oldest First)',
'thumbnail_lightbox' => 'Thumbnail with LightBox link to Fullsized Image',
'titles' => 'Titles',
'wpg2_fullsize_image' => 'Fullsized image with link to Gallery page for image (HTML)',
'wpg2_fullsize_only' => 'Fullsized image only - no link (HTML)',
'wpg2_thumbnail_lightbox' => 'Thumbnail with LightBox link to Fullsized Image (HTML)')
?>
