<?php
// Gallery2 Image Chooser pop-up window Italian lang variables - Version 2.2

// If you translate this file to your own language, please zip it and e-mail
// it to blogger (at sign) steffensenfamily (dot) com and I'll make it available
// for others and include it in the next version.  Thanks!

$g2ic_lang = array(
'about' => 'About G2Image',
'alignment_class' => "Classe di allineamento:",
'alignment_legend' => "Classe di allineamento (per funzionare il CSS deve gestire la classe 'g2image'):",
'click_advanced' => "Apertura del menù delle opzioni avanzate",
'click_image' => "Clicca su un'immagine per mostrare le opzioni",
'click_one_click' => "Inserimento dell'immagine con le impostazioni di default",
'click_options' => "Scegli il risultato dell'operazione di click su un'immagine:",
'current_album' => "Album corrente:",
'custom_url' => "URL personalizzata:",
'description' => "Descrizione:",
'description_legend' => "Testo per l'attributo 'alternate text' dell'immagine o per il link testuale:",
'display_legend' => "Opzioni di visualizzazione",
'drupal_album_legend' => 'Insert a Drupal G2 Filter tag for the current album:',
'drupal_g2_filter' => 'Drupal Gallery2 Filter',
'empty_album' => "Non ci sono foto in questo album.<br /><br />Seleziona un'altro album dalle opzioni di navigazione che si 'trovano all'inizio della pagina",
'filename' => 'Filename: ',
'filenames' => "Nomi dei files",
'g2_directory_error' => "Impossibile aprire la directory dei dati di Gallery2.  :-(",
'g2_embedded_error' => "<h3>Errore Fatale di Gallery2: impossibile attivare le funzioni Gallery2 Embedded.</h3><br />Prova ad installare il plugin WPG2 per Wordpress (http://wpg2.galleryembedded.com/) oppure verifica il percorso di Gallery2 nel file config.php.",
'g2_entities_by_id_error' => "<h3>Errore Fatale di Gallery2: impossibile ottenere le informazioni sull'immagine per questo ID di Gallery2.</h3><br />Questo è l'errore ottenuto da G2: ",
'g2_fatal_error' => "<h3>Errore Fatale di Gallery2:</h3><br />Questo è l'errore ottenuto da G2: ",
'g2_id_by_path_error' => "<br /><h3>Errore di Gallery2: impossibile ottenere l'ID di Gallery2 per il percorso richiesto.</h3><br />Questo è dovuto molto probabilmente alla presenza di un file o directory nella directory data di Gallery2 che non è stato ancora registrato come facente parte della struttura di album di Gallery2.  Tutto il resto delle funzionalit�  di questa pagina continueranno a funzionare.<br /><br />Questo è il percorso non valido: ",
'g2_id_not_found_error' => "<h3>Errore Fatale di Gallery2: impossibile ottenere l'ID di Gallery2 per questo file.</h3>Questo è l'errore ottenuto da G2: ",
'g2_image_title' => "Titolo di Gallery2:",
'go' => "Vai",
'how_insert' => "Come inserire:",
'image_title' => 'Title: ',
'img_float_left' => "Allinea a sinistra",
'img_float_right' => "Allinea a destra",
'img_centered' => "Centrato",
'img_none' => "Nessuno",
'img_normal' => "Normale",
'insert' => "Inserisci",
'insert_legend' => "Premi il pulsante per inserire l'immagine:",
'last_modification_new' => "Ultima modifica (prima i più nuovi)",
'last_modification_old' => "Ultima modifica (prima i più vecchi)",
'link_album' => "Link testuale all'album che contiene l'immagine",
'link_image' => "Link testuale all'immagine",
'name_a_to_z' => "Nome (A-z)",
'name_z_to_a' => "Nome (z-A)",
'page' => "Pagina:",
'page_navigation' => "Navigazione pagine:",
'photo_albums' => "Album di foto",
'redraw' => "Ricarica",
'sort_error' => "Errore nell'ordinamento per",
'sorted_by' => "Ordinato per:",
'subalbums' => "Sottoalbum:",
'thumbnails' => "Miniature",
'thumbnail_album' => "Miniatura con link all'album che contiene l'immagine",
'thumbnail_custom_url' => "Miniatura con link alla URL personalizzata (nella casella di testo sotto)",
'thumbnail_image' => "Miniatura con link all'immagine",
'thumbnail_only' => 'Thumbnail only - no link',
'thumbnails_per_page' => "Foto per pagina:",
'title' => "Selezionatore immagini di Gallery 2",
'title_a_to_z' => "Titolo Gallery2 (A-z)",
'title_z_to_a' => "Titolo Gallery2 (z-A)",
'url' => "URL:",
'wpg2_album_legend' => "Inserisce una tag WPG2 per l'album corrente:",
'wpg2_configuration_error' => "Errore di configurazione:<br />WPG2 è installato e attivo, ma non è stata effettuata la validazione della configurazione.<br />Configura e convalida il plugin WPG2 nel pannello di amministrazione di Wordpress.<br />Per le istruzioni fare riferimento a http://wpg2.galleryembedded.com.",
'wpg2_link_album' => "Link testuale all'album che contiene l'immagine (HTML)",
'wpg2_link_image' => "Link testuale all'immagine (HTML)",
'wpg2_tag_image' => "WPG2 tag dell'immagine",
'wpg2_thumbnail_album' => "Miniatura con link all'album che contiene l'immagine (HTML)",
'wpg2_thumbnail_custom_url' => "Miniatura con link alla URL personalizzata (nella casella di testo sotto) (HTML)",
'wpg2_thumbnail_image' => "Miniatura con link all'immagine (HTML)",
'wpg2_thumbnail_only' => 'Thumbnail only - no link (HTML)',
//
// New for version 2.2
//
'fullsize_image' => 'Fullsized image with link to Gallery page for image',
'fullsize_only' => 'Fullsized image only - no link',
'image_size' => 'Image Size',
'image_size_instructions' => 'Leave size blank the current default size of ',
'orignination_time_new' => 'Origination Time (Newest First)',
'orignination_time_old' => 'Origination Time (Oldest First)',
'thumbnail_lightbox' => 'Thumbnail with LightBox link to Fullsized Image',
'titles' => 'Titles',
'wpg2_fullsize_image' => 'Fullsized image with link to Gallery page for image (HTML)',
'wpg2_fullsize_only' => 'Fullsized image only - no link (HTML)',
'wpg2_thumbnail_lightbox' => 'Thumbnail with LightBox link to Fullsized Image (HTML)')
?>