<?php

// Gallery2 Image Chooser pop-up window Polish lang variables - Version 2.2

// Translated by Maciej Bryński.
// http://www.brynski.pl

$g2ic_lang = array(
'about' => 'O programie',
'alignment_class' => 'Wyrównianie:',
'alignment_legend' => 'Wyrównanie (musi być wspieranie przez standard CSS):',
'click_advanced' => 'Otwórz zaawansowane opcje.',
'click_image' => 'Kliknij aby uzyskać opcje zdjęcia.',
'click_one_click' => 'Wstaw używając ustawień domyślnych',
'click_options' => 'Wybierz akcję po kliknięciu na zdjęcie:',
'current_album' => 'Aktualny album:',
'custom_url' => 'Inny adres:',
'description' => 'Opis:',
'description_legend' => 'Tekst alternatywny:',
'display_legend' => 'Ustawienia wyświetlania',
'drupal_album_legend' => 'Wstaw znacznik filtru systemu Drupal dla bieżącego albumu:',
'drupal_g2_filter' => 'Filtr systemu Drupal',
'empty_album' => 'W tym albumie nie ma żadnych zdjęć.<br /><br />Wybierz inny album.',
'filename' => 'Nazwa pliku: ',
'filenames' => 'Nazwy plików',
'g2_directory_error' => 'Nie można otworzyć danych galerii.',
'g2_embedded_error' => '<h3>Bład Galerii: Nie można aktywować Galerii.</h3><br />Zainstaluj wtyczkę WPG2 dla systemu wordpress
(ze strony <a href="http://wpg2.ozgreg.com/">http://wpg2.ozgreg.com/</a>) lub sprawdź poprawność istniejącej instalacji.<br /><br />Dla innych systemów sprawdź poprawność ścieżki do Galerii w pliku config.php.',
'g2_entities_by_id_error' => '<h3>Bład Galerii: Nie można pobrać zdjęcia o podanym identyfikatorze.</h3><br />Błąd wygenerowany przez Galerię: ',
'g2_fatal_error' => '<h3>Bład Galerii:</h3><br />Błąd wygenerowany przez Galerię: ',
'g2_id_by_path_error' => '<br /><h3>Bład Galerii: Nie można pobrać identyfikatora o podanej ścieżce.</h3><br />Prawdopodobnie podany plik nie jest dodany do Galerii.<br /><br />Niepoprawna ścieżka: ',
'g2_id_not_found_error' => '<h3>Fatal Gallery2 Error: Cannot get the Gallery2 ID for this file.</h3>Here\'s the error from G2: ',
'g2_image_title' => 'Tytuł:',
'go' => 'Idź',
'how_insert' => 'Jak wstawić:',
'image_title' => 'Tytuł: ',
'img_float_left' => 'Do lewej',
'img_float_right' => 'Do prawej',
'img_centered' => 'Wyśrodkowany',
'img_none' => 'Brak',
'img_normal' => 'Normalny',
'insert' => 'Wstaw',
'insert_legend' => 'Press button to insert image:',
'last_modification_new' => 'Data modyfikacji (od najnowszych)',
'last_modification_old' => 'Last Modification (od najstarszych)',
'link_album' => 'Link tekstowy do nadrzędnego albumu',
'link_image' => 'Link tekstowy do zdjęcia',
'name_a_to_z' => 'Nazwa pliku (A-z)',
'name_z_to_a' => 'Nazwa pliku (z-A)',
'page' => 'Strona:',
'page_navigation' => 'Nawigacja:',
'photo_albums' => 'Photo Albums',
'redraw' => 'Odśwież',
'sort_error' => 'Błąd przy sortowaniu po',
'sorted_by' => 'Porządek sortowania:',
'subalbums' => 'Albumy:',
'thumbnails' => 'Miniaturki',
'thumbnail_album' => 'Miniaturka z linkiem do nadrzędnego albumu',
'thumbnail_custom_url' => 'Miniaturka z innym linkiem (z pola powyżej)',
'thumbnail_image' => 'Miniaturka z linkiem do zdjęcia',
'thumbnail_only' => 'Miniaturka bez linku',
'thumbnails_per_page' => 'Na stronę:',
'title' => 'Wybierz zdjęcie z Galerii',
'title_a_to_z' => 'Tytuł (A-z)',
'title_z_to_a' => 'Tytuł (z-A)',
'url' => 'Adres:',
'wpg2_album_legend' => 'Wstaw znacznik WPG2 dla bieżącego albumu:',
'wpg2_configuration_error' => 'Błąd konfiguracju:<br />WPG2 nie zostało sprawdzone.<br />Skonfiguruj i sprawdź WPG2 w panelu konfiguracji WordPress.',
'wpg2_link_album' => 'Link tekstowy do nadrzędnego albumu (HTML)',
'wpg2_link_image' => 'Link tekstowy do zdjęcia (HTML)',
'wpg2_tag_image' => 'Znacznik zdjęcia WPG2',
'wpg2_thumbnail_album' => 'Miniaturka z linkiem do nadrzędnego albumu (HTML)',
'wpg2_thumbnail_custom_url' => 'Miniaturka z innym linkiem (z pola powyżej) (HTML)',
'wpg2_thumbnail_image' => 'Miniaturka z linkiem do zdjęcia (HTML)',
'wpg2_thumbnail_only' => 'Miniaturka bez linku (HTML)',
//
// New for version 2.2
//
'fullsize_image' => 'Fullsized image with link to Gallery page for image',
'fullsize_only' => 'Fullsized image only - no link',
'image_size' => 'Image Size',
'image_size_instructions' => 'Leave size blank the current default size of ',
'orignination_time_new' => 'Origination Time (Newest First)',
'orignination_time_old' => 'Origination Time (Oldest First)',
'thumbnail_lightbox' => 'Thumbnail with LightBox link to Fullsized Image',
'titles' => 'Titles',
'wpg2_fullsize_image' => 'Fullsized image with link to Gallery page for image (HTML)',
'wpg2_fullsize_only' => 'Fullsized image only - no link (HTML)',
'wpg2_thumbnail_lightbox' => 'Thumbnail with LightBox link to Fullsized Image (HTML)')
?>