<?php

// Gallery2 Image Chooser pop-up window Chinese lang variables - Version 2.2

// If you translate this file to your own language, please zip it and e-mail
// it to blogger (at sign) steffensenfamily (dot) com and I'll make it available
// for others and include it in the next version.  Thanks!

$g2ic_lang = array(
'about' => '關於 G2Image',
'alignment_class' => '對齊級別：',
'alignment_legend' => '對齊級別（CSS必需支援 g2image classes 級別才能發生效用）：',
'click_advanced' => '開啟進階設定選單',
'click_image' => '在圖像上按滑鼠會出現圖像選項。',
'click_one_click' => '使用預設方式插入',
'click_options' => '在圖像上按滑鼠鍵的動作：',
'current_album' => '目前相簿：',
'custom_url' => '自定網址：',
'description' => '描述：',
'description_legend' => '圖像或文字鏈接的替代文字說明：',
'display_legend' => '顯示選項',
'drupal_album_legend' => '插入目前相簿的 Drupal G2 過濾器標籤：',
'drupal_g2_filter' => 'Drupal Gallery2 過濾器',
'empty_album' => '這個相簿中沒有照片。<br /><br />請在上面的導覽選項中另選一個相簿。',
'filename' => '檔名：',
'filenames' => '檔名：',
'g2_directory_error' => '無法打開 Gallery2 資料目錄。 :-(',
'g2_embedded_error' => '<h3>嚴重 Gallery2 錯誤：無法啟動 Gallery2 內嵌功能。</h3><br />如果你是使用 WordPress，請安裝 WPG2 外掛模組
（位於 <a href="http://wpg2.galleryembedded.com/">http://wpg2.galleryembedded.com/</a>）或確認你在 G2Image Popup Options 管理面板中的 Gallery2 路徑。<br />
在其他平台上，請確認 config.php 中 Gallery2 的路徑。',
'g2_entities_by_id_error' => '<h2>嚴重 Gallery2 錯誤：</h2><br />無法取得這個 Gallery2 ID 的圖像資訊。<br />G2 傳回的錯誤：',
'g2_fatal_error' => '<h2>嚴重 Gallery2 錯誤：</h2><br />G2 傳回的錯誤：',
'g2_id_by_path_error' => '<h2>嚴重 Gallery2 錯誤：</h2><br />無法取得要求路徑的 Gallery2 ID。<br />G2 傳回的錯誤：',
'g2_id_not_found_error' => '<h2>嚴重 Gallery2 錯誤：</h2><br />無法取得這個檔案的 Gallery2 ID。<br />G2 傳回的錯誤：',
'g2_image_title' => 'Gallery2 主題：',
'go' => '前往',
'how_insert' => '插入方式：',
'image_title' => '主題：',
'img_float_left' => '浮動對左',
'img_float_right' => '浮動對右',
'img_centered' => '對中',
'img_none' => '無',
'img_normal' => '正常',
'insert' => '插入',
'insert_legend' => '按下按鈕以插入圖像：',
'last_modification_new' => '上次更新日期（最新的在前）',
'last_modification_old' => '上次更新日期（最舊的在前）',
'link_album' => '指到上層相簿的文字鏈接',
'link_image' => '指到圖像的文字鏈接',
'name_a_to_z' => '檔案名稱（A-z）',
'name_z_to_a' => '檔案名稱（z-A）',
'page' => '頁數：',
'page_navigation' => '頁面導覽：',
'photo_albums' => '相簿',
'redraw' => '重新顯示',
'sort_error' => '排序方式錯誤',
'sorted_by' => '排序方式：',
'subalbums' => '子相簿：',
'thumbnails' => '縮略圖',
'thumbnail_album' => '指到上層相簿的縮略圖',
'thumbnail_custom_url' => '指到自定網址（在下列文字框中）的縮略圖',
'thumbnail_image' => '指到圖像的縮略圖',
'thumbnail_only' => '只顯示縮略圖：不含鏈接',
'thumbnails_per_page' => '每頁項數：',
'title' => '選取 Gallery 2 圖像',
'title_a_to_z' => 'Gallery 2 主題（A-z）',
'title_z_to_a' => 'Gallery 2 主題（z-A）',
'url' => '網址：',
'wpg2_album_legend' => '插入目前相簿的 WPG2 標籤：',
'wpg2_configuration_error' => '組態設定錯誤：<br />WPG2 已用，可是並未通過驗証手續。<br />請在 WordPress 管理面板中設定並驗証 WPG2。<br />說明可在 http://wpg2.galleryembedded.com 網站中找到。',
'wpg2_link_album' => '指到上層相簿的文字鏈接（HTML）',
'wpg2_link_image' => '指到圖像的文字鏈接（HTML）',
'wpg2_tag_image' => '圖像的 WPG2 標籤',
'wpg2_thumbnail_album' => '指到上層相簿的縮略圖（HTML）',
'wpg2_thumbnail_custom_url' => '指到自定網址（在下列文字框中）的縮略圖（HTML）',
'wpg2_thumbnail_image' => '指到圖像的縮略圖（HTML）',
'wpg2_thumbnail_only' => '只顯示縮略圖：不含鏈接（HTML）',
//
// New for version 2.2
//
'fullsize_image' => 'Fullsized image with link to Gallery page for image',
'fullsize_only' => 'Fullsized image only - no link',
'image_size' => 'Image Size',
'image_size_instructions' => 'Leave size blank the current default size of ',
'orignination_time_new' => 'Origination Time (Newest First)',
'orignination_time_old' => 'Origination Time (Oldest First)',
'thumbnail_lightbox' => 'Thumbnail with LightBox link to Fullsized Image',
'titles' => 'Titles',
'wpg2_fullsize_image' => 'Fullsized image with link to Gallery page for image (HTML)',
'wpg2_fullsize_only' => 'Fullsized image only - no link (HTML)',
'wpg2_thumbnail_lightbox' => 'Thumbnail with LightBox link to Fullsized Image (HTML)')
?>